"""
This module contains constants and default values for the simulation.
"""

# default attributes and parameters of simulation agents

#: default multiplicand applied to euclidean distance to approximate a travelling distance
DEFAULT_DISTANCE_FACTOR = 1.3

#: default walking speed of Person objects (in m/s)
DEFAULT_WALKING_SPEED = 1.1

#: default dwell time of service vehicles
DEFAULT_DWELL_TIME = 30

# default patience
DEFAULT_PATIENCE = None

# keys and names used in the simulation

#: name of the population containing the simulation stop points
STOP_POINT_POPULATION = "stop_point"

#: agent_type of the agents generated by PublicTransportOperator
PUBLIC_TRANSPORT_TYPE = "public_transport"

#: required DataFrame columns of the table describing the stop points when calling add_stops()
ADD_STOPS_COLUMNS = ["stop_id", "stop_name", "stop_lat", "stop_lon"]

#: name of the json schema for PT_parameters
PT_PARAMETERS_SCHEMA = "PT_parameters.schema.json"

#: default name of parameters file
DEFAULT_PARAMS_NAME = "Params.json"

# base leaving codes

#: default leaving code, when the loop terminates without LeavingSimulation exception
DEFAULT_LEAVE = "DEFAULT"

#: leaving code signaling a completed loop
SUCCESS_LEAVE = "SUCCESS"

#: leaving code signaling the end of the simulation
END_OF_SIM_LEAVE = "END_OF_SIM"

#: leaving code signaling a simulation error
SIM_ERROR_LEAVE = "SIM_ERROR"

#: dict of base leaving codes and their descriptions
BASE_LEAVING_CODES = {
        DEFAULT_LEAVE: "No explicit leave call",
        SUCCESS_LEAVE: "Successful loop",
        END_OF_SIM_LEAVE: "End of simulation",
        SIM_ERROR_LEAVE: "Simulation error"
}

# filename formats

#: format of the KPI output files
KPI_FORMAT = "{scenario}_{kpi_output}.csv.bz2"

#: format of the geojson output files
GEOJSON_FORMAT = "{scenario}.geojson"

#: format of the trace output files
TRACE_FORMAT = "{scenario}_traces.txt"

#: format of the ALIENS operators usage diagram
OPERATORS_USAGE_FORMAT = "{prefix}_operators.png"

#: format of the ALIENS objective function graph
OBJECTIVE_GRAPH_FORMAT = "{prefix}_objective.png"

# other constants

#: default maximum distance between stop and node before extending graph
DEFAULT_MAX_STOP_DISTANCE = 100
