"""
This module contains constants and default values for the simulation.
"""

# default attributes and parameters of simulation agents

#: default multiplicand applied to euclidean distance to approximate a travelling distance
DEFAULT_DISTANCE_FACTOR = 1.3

#: default walking speed of Person objects (in m/s)
DEFAULT_WALKING_SPEED = 1.1

#: default dwell time of service vehicles
DEFAULT_DWELL_TIME = 30

# default patience
DEFAULT_PATIENCE = None

# keys and names used in the simulation

#: name of the population containing the simulation stop points
STOP_POINT_POPULATION = "stop_point"

#: agent_type of the agents generated by PublicTransportOperator
PUBLIC_TRANSPORT_TYPE = "public_transport"

#: required DataFrame columns of the table describing the stop points when calling add_stops()
ADD_STOPS_COLUMNS = ["stop_id", "stop_name", "stop_lat", "stop_lon"]

#: name of the json schema for PT_parameters
PT_PARAMETERS_SCHEMA = "PT_parameters.schema.json"

#: default name of parameters file
DEFAULT_PARAMS_NAME = "Params.json"

# filename formats

#: format of the KPI output files
KPI_FORMAT = "{scenario}_{kpi_output}.csv.bz2"

#: format of the geojson output files
GEOJSON_FORMAT = "{scenario}.geojson"

#: format of the ALIENS operators usage diagram
OPERATORS_USAGE_FORMAT = "{prefix}_operators.png"

#: format of the ALIENS objective function graph
OBJECTIVE_GRAPH_FORMAT = "{prefix}_objective.png"

# ids and links for importing files from Tellae's Google Drive

# link format for importing files (can be used with wget)
google_drive_download_format = "https://docs.google.com/uc?export=download&id={}"

# id of the osm graphs archive
OSM_GRAPHS_ID = "1_QErckpf-cgcJfC2Il3WS4SdlLEP0Lmt"

# id of the graph speeds archive
GRAPH_SPEEDS_ID = "18vgoP8EyyeUIhdbCP8Jp8UVvJgOdGlX2"

# ids of the example scenarios archive of each model
example_scenarios = {
    "SB_VS": "1uFP_chQiHi4WC40C38MKuWxpJq_oWWlH",
    "SB_VS_R": "1Z4J4VhXNHfjQBYo11bDpLCq04lKBkLxv",
    "FF_VS": "1E7a22VwiweNd5jOzHn5aElOTaczYNfQn"
}
