name: Black formatting

on:
  push:
    branches: [ main, main2 ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--line-length 100 --check --diff"